### ISSUE TITLE
Inference using Blink API

### ISSUE THREAD

**Issue by hepesu** [TheFoundryVisionmongers/nuke-ML-server#1]
Thanks for sharing this great project and its plugin to introducing deep learning into Nuke with simple steps.

I am also doing some similar work in Nuke, but my solution is Blink API. Blink API has ability to use cross-platform GPU and CPU computing, and can work like OpenGL which has been used for cross-platform inference (Tensorflow.js using WebGL). So it is suitable for building cross-platform inference engine and is easy for real world deployment. As for using full pipeline deep learning framework, installing full deep learning environment is still hard nowadays, especially for windows user. Also if users do not have Nvidia graphic card, it might be a problem for them to use GPU. Because of these, I think Blink API (OpenGl/OpenCl or inference engine like TensorRT, TVM...) is more suitable for near future use. 

I have done a small experiment using Blink API for inference, and it worked. The model is a sequential convolutional neural network with 10 conv2D layers, which can achieve most low-level visual tasks such as super-resolution, deblur and denoise. The model was hard coded in C++ plugin. Complex model support can be enabled by introducing computational graph. The implement of conv2D is the simplest convolution, but the speed is acceptable. 

Here is the example code for the kernel (conv2D 9x9 64 with batch nomalization and relu).
```c++
// Copyright (c) 2019 Hepesu Animation Toolkits Project. All Rights Reserved.

#define epsilon 1e-7

inline float batchNorm(float x, float mean, float var, float gamma, float beta){
  return (x - mean) / (sqrt(var) + epsilon) * gamma + beta;
}

inline float relu(float x){
  return max(0.0f, x);
}

kernel ConvBlockAKernel : public ImageComputationKernel<ePixelWise>
{
  Image<eRead, eAccessRanged2D, eEdgeConstant> src;
  Image<eWrite> dst;

param:
  float weight[81];
  float bias;
  
  float gamma;
  float beta;
  float mean;
  float var;
  
  int outputChannel;
  
local:
  int2 _filterOffset;
  int2 _kernelSize;

  void init()
  {
    _kernelSize[0] = 9;
    _kernelSize[1] = 9;

   int2 filterRadius(_kernelSize[0] / 2, _kernelSize[1] / 2);

    _filterOffset[0] = -filterRadius[0];
    _filterOffset[1] = -filterRadius[1];

    src.setRange(-filterRadius[0], -filterRadius[1], filterRadius[0], filterRadius[1]);
  }

  void process() {
    // Init value with 0.0
    float value = 0.0;
    
    for (int in_channel = 0; in_channel < src.kComps; in_channel++){
      // Iterate in ks x ks range
        for(int j = 0; j < _kernelSize[1]; j++) {
          for(int i = 0; i < _kernelSize[0]; i++) {
            value += weight[j * 9 + i] * src(i + _filterOffset[0], j + _filterOffset[1], in_channel);
        }
      }
    }
    
    // Add bias then bn and relu
    dst(outputChannel >= dst.kComps ? dst.kComps - 1 : outputChannel) = relu(batchNorm(value + bias, mean, var, gamma, beta));
  }
};
```
Here is the code for calling this kernel in plugin. I am using setParamValue to pass weights of the model. If the weights are huge, this can be done by passing them as an image source.
```c++
// Copyright (c) 2019 Hepesu Animation Toolkits Project. All Rights Reserved.

Blink::Kernel blockA(_convBlockAWideProgram, computeDevice, imagesIA, kBlinkCodegenDefault);
for (int outChan = 0; outChan < 64; ++outChan){
	float weights[81];
	for (int i = 0; i < 81; ++i)
		weights[i] = dequantize(wide_block1_weight[outChan][i], wide_block1_weight_max, wide_block1_weight_min);
	blockA.setParamValue("weight", weights, 81);
	blockA.setParamValue("bias", dequantize(wide_block1_bias[outChan], wide_block1_bias_max, wide_block1_bias_min));

	blockA.setParamValue("mean", dequantize(wide_block1_mean[outChan], wide_block1_mean_max, wide_block1_mean_min));
	blockA.setParamValue("var", dequantize(wide_block1_var[outChan], wide_block1_var_max, wide_block1_var_min));
	blockA.setParamValue("gamma", dequantize(wide_block1_gamma[outChan], wide_block1_gamma_max, wide_block1_gamma_min));
	blockA.setParamValue("beta", dequantize(wide_block1_beta[outChan], wide_block1_beta_max, wide_block1_beta_min));

	blockA.setParamValue("outputChannel", outChan);

	blockA.iterate();
}
```
The performance can be further improved by using winograd or GEMM which is used in most deep learning framework. With these, the inference can be supported by all platform, even for Nuke 9, and users do not need to installing any other software or drivers. Also the inference is just done by stripe, so it looks like most node, users do not need to wait for whole image which may cost very long time and huge memory. But due to limitations of Blink API, the implementation of general inference engine (with computational graph) is not easy. The GEMM and a complex computational graph might exceed the limit of Blink API. So for latest nuke, I prefer to use inference engine TensorRT to do the jobs.

The server solution is great for testing newest deep learning technology, and I think this is the main stream for the future. But it would be great, if the inference can be done in the local machine. customers can use deep learning tools just like other simple nodes.

**Comment by ringdk** [comment]
Glad to hear you're enjoying the project, and thanks for sharing your awesome Blink API example!

We're also looking into the idea of using Blink for inference, for the same reasons you mentioned (cross-platform, cross hardware). We also have similar concerns as you (performance, complexity limitations). When we get some time we'll be exploring how to map an arbitrary graph to a set of Blink kernels, ideally in a way that lets a user open their own graph in say a Blink DNN node.

We'll keep you posted if / when we make progress on the above. In the mean-time we're focusing on extending the server, and adding model skeletons to make training of custom problems easier. Thanks again!

**Comment by hepesu** [comment]
Thank you! 

I am looking forward to hearing new progress!
