### ISSUE TITLE
Docker image crashes without AVX instructions

### ISSUE THREAD

**Issue by samhodge** [TheFoundryVisionmongers/nuke-ML-server#10]
```
[kognat@vxfhost Server]$ sudo docker run --runtime=nvidia -v /home/kognat/dev/nuke-ML-server/Models:/workspace/ml-server/models:ro -it nuke-ml-magic:latest
[sudo] password for kognat: 
root@a1b2b7bf4646:/workspace/ml-server# python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2019-05-25 07:49:46.583944: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted (core dumped)
```

Party over dude.

**Comment by samhodge** [comment]
Workaround is here:
https://github.com/yaroslavvb/tensorflow-community-wheels/issues/69#issuecomment-478763464

**Comment by samhodge** [comment]
doesnt effect the Caffe2 models

**Comment by ringdk** [comment]
Thanks for heads-up! We haven't seen that issue before.

At the moment we're not planning on rebuilding and supporting our own TF libraries. We'll add it to our list of known issues. Thanks again!

**Comment by samhodge** [comment]
Lack of AVX instructions is a curiosity relevant only to ancient hardware, like mine.

**Comment by ringdk** [comment]
Lol! It's not as uncommon as you think, we've hit similar issues before with Blink.
