### ISSUE TITLE
Software license conflicts

### ISSUE THREAD

**Issue by dekekincaid** [TheFoundryVisionmongers/nuke-ML-server#13]
Hi Folks

The license for the project is listed as Apache License, Version 2.0.  At the same time the readme and the MLClient node reads: "This is strictly non-commercial".  These are legally in conflict.  The Apache license you assigned to the code means I can pretty much do whatever I want with the code and sell it to whomever I want.  Also the license is irrevocable.

Copied from the include Apache License 2.0 in this project:

> 2. Grant of Copyright License. Subject to the terms and conditions of
> this License, each Contributor hereby grants to You a perpetual,
> worldwide, non-exclusive, no-charge, royalty-free, irrevocable
> copyright license to reproduce, prepare Derivative Works of,
> publicly display, publicly perform, sublicense, and distribute the
> Work and such Derivative Works in Source or Object form.

You really should remove the "This is strictly non-commercial" part from the readme and the node.

**Comment by samhodge** [comment]
Even the COCO dataset it was trained on is CC3.0

**Comment by ringdk** [comment]
Hello!

Thanks both for bringing that to our attention. We don't want to impose any restrictions or constraints on the Apache license. We also think the current licensing is a bit confusing, where it's all Apache except for some files relating to the 'DensePose' model under CC non-commercial.

To make things clearer we've removed all 'strictly non-commercial' mentions, as well as the 'DensePose' model to ensure everything is covered by the unmodified Apache 2.0 license.

Thanks again!
