### ISSUE TITLE
Python3 and Protobuf

### ISSUE THREAD

**Issue by fdan** [TheFoundryVisionmongers/nuke-ML-server#17]
Hi folks,

I'm modifying the server to run with Python3, as my ML environments require it.  

I think I may have ran into some issues with protobuf.  In my server output, I see the following:

```
Server -> Listening on port: 55555
Server -> Receiving message of size: 6
Server -> 6 bytes read
Server -> Message parsed
Server -> Received info request
Server -> Serializing message
Server -> Sending response message of size: 98
Server -> -----------------------------------------------
```

But the client output says, reporting it read data of size 0, instead of 98

```
Client -> Connected to 172.17.0.2
Client -> Sending info request
Client -> Created message
Client -> Serialized message
Client -> Created char array of length 6
Client -> Copied to char array
Client -> Message sent
Client -> Reading header data
Client -> Reading data of size: 0
Client -> Deserializing message
Client -> Closed connection
```
This is my first time using protobuf, so I thought I'd just enquire if there's anything obvious I should be looking for in terms of why it works with Python2 and not Python3,

cheers

**Comment by ringdk** [comment]
Hi!

Thanks for sending that in. Internally we've been testing a migration to
Python 3 and I'm not sure if we've hit this one. Let us get back to you!

**Comment by johannabar** [comment]
Hi there, we have actually migrated the server from python2 to python3 in May!

You can pull the latest version of this repo which is by default in python3 (and still python2 compatible). If you previously built the python2 dockerfile, you will need to rebuild your python3 Docker image [Plugins/Server/Dockerfile](https://github.com/TheFoundryVisionmongers/nuke-ML-server/blob/master/Plugins/Server/Dockerfile) following the [installation instructions](https://github.com/TheFoundryVisionmongers/nuke-ML-server/blob/master/INSTALL.md#install-docker) and then it should work fine. Please let us know if you face any more issues!

**Comment by fdan** [comment]
Ahah, my bad, I cloned the repo before then and had neglected to pull for a while, will check out now.
