### ISSUE TITLE
Turing based card compatibility

### ISSUE THREAD

**Issue by samhodge** [TheFoundryVisionmongers/nuke-ML-server#2]
Hey I know that CUDA 10 and CUDNN 7.4 at least are required for Turing based Cards the RTX range, has this been tested on Turing cards?

**Comment by samhodge** [comment]
I see the docker image is installing conda packages for cudatoolkit-10.0.130 and cudnn 7.5

**Comment by ringdk** [comment]
Hello! The Dockerfile we're using is based on 'cuda:9.0-cudnn7-devel-ubuntu16.04', can you say where you found the cudatoolkit-10.0.130 and cudnn 7.5 conda install commands?

Most of our testing is performed on Turing (Titan) RTX cards, where it seems to run correctly.

**Comment by samhodge** [comment]
I was watching the shell while it was installing. Several of the deep learning packages must require later versions of CUDA and CuDNN and I see it pull in 10.0 and 7.5 respectively as dependencies for these packages
