### ISSUE TITLE
CMake 3 is not part of CentOS 7

### ISSUE THREAD

**Issue by samhodge** [TheFoundryVisionmongers/nuke-ML-server#3]
Is there a reason why CMake 3 is a requirement?

**Comment by dekekincaid** [comment]
A majority of vfxplatform libraries requires cmake 3 or higher these days.

**Comment by samhodge** [comment]
Seems like it is more of a CentOS 7 issue then

**Comment by ringdk** [comment]
Hello! We use CMake 3 for our internal build systems, and we use ML server a lot for our own development. The ML server may work on older versions of CMake but we haven't tested it extensively, and features we'd like to add in future may require CMake 3.
