### ISSUE TITLE
CPU only inferrence?

### ISSUE THREAD

**Issue by samhodge** [TheFoundryVisionmongers/nuke-ML-server#6]
Many visual effect facilities have large investments in CPU only render farms, is it possible to do inference on a distributed CPU render farm?

**Comment by samhodge** [comment]
Sorry I realised it is unique to the model, but does DensePose have a CPU only mode?

**Comment by ringdk** [comment]
At the moment, the server can technically perform inference using the CPU, but it depends on the framework and architecture of the particular model. For example, the TensorFlow and Caffe frameworks in the Docker image are the GPU versions, I'm not sure how they'd behave falling back to CPU. However the included OpenCV library will work on CPU.

Regarding DensePose and Mask R-CNN, they currently require a GPU for inference.

**Comment by samhodge** [comment]
Yeah I sort of knew most of what you have told me:

For Tensorflow you can use CPU or GPU at will as follows:
https://www.tensorflow.org/guide/graphs#placing_operations_on_different_devices

The issue about CPU only inference of Detectron was logged by me some time ago:

https://github.com/facebookresearch/Detectron/issues/54
