### ISSUE TITLE
Offline installation?

### ISSUE THREAD

**Issue by samhodge** [TheFoundryVisionmongers/nuke-ML-server#7]
Is it possible to install the software without access to the internet if the files are downloaded in advance?

**Comment by ringdk** [comment]
Good question, we think it's possible but haven't tried it.

Thinking about it, you'll need internet access to clone the repo, download & build third-party libraries (such as protobuf & Docker), and finally to build the Docker image. Once the Docker image is built you should be able to run the Docker container offline.

We'll give it a whirl this week and report back!

**Comment by samhodge** [comment]
Yeah should be pretty easy to test, just throw in a drop all traffic outside of your local subnet range with an iptables rule and see if everything keeps running.

**Comment by ringdk** [comment]
Hello! Very late reply, sorry, but a quick test recently allowed me to move the docker image from one CentOS machine to a very similar CentOS machine and create a container there. So it seems possible, but can't guarantee it'll work in all cases.
